### ISSUE TITLE
Reconnection sample please

### ISSUE THREAD

**Issue by haf** [EventStore/EventStore.Samples.Dotnet#5]
Hi there,

Could you please expand the samples with a reconnection sample?

We're having the issue of a broken TCP connection not properly reinitialising the subscription, despite having a recursive subscription function, and as well, the callback for the catch-up-subscription going live firing again.

Thanks,
Henrik

**Comment by gregoryyoung** [comment]
Which type of subscription?

**Comment by haf** [comment]
CatchUp. It's a funky error that only happens once in a while, and we can't reproduce it easily by shutting down/restarting ES either... So a sample just on how to reconnect lets us rule out at least that part for sure. :)

**Comment by haf** [comment]
Btw, if you'd be open for an hour or two of consulting to reproduce/find the error through the logs I'd be very interested in buying that. Yesterday it stopped our read models from working, and today it stopped our integrations.

**Comment by gregoryyoung** [comment]
Can you post your code?

**Comment by haf** [comment]
No because you want it in C# and I only can give you F#. But would it be possible to get a recommended reconnection sample please? The subscriptions cut out today as well and I don't know how to debug it.

Again, is it possible to purchase some consulting hours from you guys?

**Comment by hayley-jean** [comment]
We are aware of a couple of issues in catchup subscriptions, namely https://github.com/EventStore/EventStore/issues/1127, https://github.com/EventStore/EventStore/issues/929, and this one on [google groups](https://groups.google.com/forum/#!searchin/event-store/subscription/event-store/AdKzv8TxabM/6RzudeuAAgAJ) which has some sample code on resubscribing.

If these aren't the issues you are seeing, could you post a sample of your code (F# is fine) with a bit more of an explanation on what you are seeing?

For enquiries about consulting, could you please email chris.watt at geteventstore dot com

**Comment by haf** [comment]
Did you create the examples?
