### ISSUE TITLE
Sample in .NET Core?

### ISSUE THREAD

**Issue by FantasticFiasco** [EventStore/EventStore.Samples.Dotnet#6]
Has there been any demand for providing a sample application in .NET Core? I'm normally a C# developer but use Debian daily, and cannot run this sample because its dependencies to .NET Framework.

If there is any interest for .NET Core, I would happily provide you with a port of this sample.

**Comment by gregoryyoung** [comment]
I believe this will run on mono well it did the last time I checked (I am linux first and many are OSX first which is a big part of why ES stuff has always worked outside of windows!). 

There is a .NET core client, making this (or another) sample work off it should be a relatively easy piece of work.

**Comment by FantasticFiasco** [comment]
Mono is a good platform, but I instinctively chose the Docker track in the [Getting started guide](https://eventstore.org/docs/getting-started/index.html?tabs=tabid-3%2Ctabid-dotnet-client%2Ctabid-dotnet-client-connect%2Ctabid-4#install-and-run-event-store), where the guide is referring to `EventStore.Client` when it possibly instead should refer to `ClientAPI.NetCore`?

I like Mono, but cannot think other than its importance will diminish with the rise of .NET Core, especially when we as developers see the amount of investment Microsoft is pouring into it, as well as its performance statistics, something I would guess Mono isn't getting close to.

Back to the subject. I also think porting the sample application would be easy. I would change as little as possible, but possibly add a docker compose file making it easier to start the compete stack. What do you think?

**Comment by gregoryyoung** [comment]
There are some places mono is still *far* superior. As example have you tried installs where no mono is installed? :+1:!!

I am all for porting it, I also agree it should be pretty easy. What you suggest seems prudent.

**Comment by FantasticFiasco** [comment]
> There are some places mono is still far superior
I'll have to trust you on that :-)

Can you create an empty repo, I'll fork it an provide you with a PR in a couple of days?

**Comment by ChrisChinchilla** [comment]
I got these to work on my Mac (I think). But I will double check asap as we will integrate these better into the docs soon, so people can follow along and download a sample etc.

**Comment by FantasticFiasco** [comment]
Still, even though .NET can run under Mono, _modern_ (I cringe when I write this) C# developers will look for .NET Core samples.

Is there any progress in creating the empty .NET Core samples repo I can put the implementation in?

**Comment by FantasticFiasco** [comment]
Close due to inactivity
